name: Data Scraping and Notification

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 matplotlib

      - name: Run script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python main.py

      - name: Commit changes
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add clan_data.json
          git commit -m 'Update clan data'
          git remote add origin_with_auth "https://github.com/TheAngel6/tt.io-graph.git"
          git push --quiet --set-upstream origin_with_auth main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

